[build]
  command = "yarn && lerna bootstrap && yarn build"
  functions = "functions/"
  publish = "apps/web/public/"

[build.environment]
  NODE_VERSION = "12.16.1"
  YARN_VERSION = "1.22.4"
  REACT_APP_ENVIRONMENT = "netlify"
